artifact_location: file:C:/Users/Admin/Desktop/CacapDetect/runs/mlflow/988418598198188559
creation_time: 1782887828024
experiment_id: '988418598198188559'
last_update_time: 1782887828024
lifecycle_stage: active
name: C:\Users\Admin\Desktop\CacapDetect\ia_module\models\runs
