artifact_location: file:C:/Users/Admin/Desktop/CacapDetect/ia_module/runs/mlflow/503513592678630511
creation_time: 1782887348167
experiment_id: '503513592678630511'
last_update_time: 1782887348167
lifecycle_stage: active
name: C:\Users\Admin\Desktop\CacapDetect\ia_module\models\runs
